"""Build a read-only-table RV32I ELF and a Ripes-editor compatibility copy.
Usage: python build_rv32i.py [--cc PATH] [--source-only]
Supports RISC-V GCC, clang+lld, or Zig's bundled clang+lld.
"""
import argparse
import os
import shutil
import struct
import subprocess
from pathlib import Path

ROOT = Path(__file__).resolve().parent
TABLES = ('pdb_permutation', 'pdb_orientation', 'perm_trans', 'ori_trans')

def compatibility_copy(render=False):
    source = (ROOT / 'solver_rv32i.s').read_text(encoding='utf-8')
    if render:
        source = source.replace('.include "led_renderer.inc"',
                                (ROOT / 'led_renderer.inc').read_text(encoding='utf-8'))
    lines = []
    active = True
    for line in source.splitlines():
        if line.strip() == '.if RENDER':
            active = render
            continue
        if line.strip() == '.endif':
            active = True
            continue
        if not active or line.startswith('.equ RENDER,'):
            continue
        if line.startswith('.section .rodata') or line.startswith('.section .bss'):
            line = '.data'
        elif line.startswith('.option '):
            continue
        elif line.startswith('.balign '):
            line = line.replace('.balign ', '.align ', 1)
        lines.append(line)
    note = ('# GENERATED by build_rv32i.py; edit solver_rv32i.s instead.\n'
            '# Ripes editor compatibility: tables are in .data, NOT a read-only section.\n'
            '# Use solver_rv32i.elf for the assignment read-only section requirement.\n')
    name = 'solver_rv32i_led_ripes.s' if render else 'solver_rv32i_ripes.s'
    (ROOT / name).write_text(note + '\n'.join(lines) + '\n', encoding='utf-8')

def verify_elf(path):
    blob = path.read_bytes()
    if blob[:7] != b'\x7fELF\x01\x01\x01':
        raise ValueError('Expected a little-endian ELF32 executable')
    h = struct.unpack_from('<16sHHIIIIIHHHHHH', blob)
    _, kind, machine, _, entry, phoff, shoff, flags, _, phsize, phnum, shsize, shnum, names_index = h
    if kind != 2 or machine != 243 or flags & 1:
        raise ValueError('Expected an RV32 executable without compressed instructions')
    sections = [struct.unpack_from('<IIIIIIIIII', blob, shoff + i * shsize) for i in range(shnum)]
    names = sections[names_index]
    strings = blob[names[4]:names[4] + names[5]]
    def string(data, offset):
        return data[offset:data.index(b'\0', offset)].decode()
    by_name = {string(strings, s[0]): (i, s) for i, s in enumerate(sections)}
    ro_index, ro = by_name['.rodata']
    text = by_name['.text'][1]
    bss = by_name['.bss'][1]
    if ro[2] != 2 or bss[1] != 8 or bss[2] != 3:
        raise ValueError('Expected read-only allocated .rodata and writable NOBITS .bss')
    loads = [struct.unpack_from('<IIIIIIII', blob, phoff + i * phsize) for i in range(phnum)]
    matching = [p for p in loads if p[0] == 1 and p[2] <= ro[3] and ro[3] + ro[5] <= p[2] + p[5]]
    if not matching or any(p[6] != 4 for p in matching):
        raise ValueError('.rodata must be contained in an R-only PT_LOAD segment')
    sym = by_name['.symtab'][1]
    sym_strings = sections[sym[6]]
    st = blob[sym_strings[4]:sym_strings[4] + sym_strings[5]]
    symbols = {}
    for off in range(sym[4], sym[4] + sym[5], sym[9]):
        n, value, size, info, other, index = struct.unpack_from('<IIIBBH', blob, off)
        symbols[string(st, n)] = (value, index)
    for name in TABLES:
        if symbols[name][1] != ro_index:
            raise ValueError(name + ' is outside .rodata')
    if symbols['_start'][0] != entry:
        raise ValueError('ELF entry differs from _start')
    total = sum(s[5] for name, (_, s) in by_name.items() if name in ('.rodata', '.data', '.bss'))
    if total > 131072:
        raise ValueError('Static data exceeds 128 KiB')
    print('ELF verified: entry=0x%x; .text=%d; .rodata=%d; .bss=%d; static=%d bytes'
          % (entry, text[5], ro[5], bss[5], total))
    print('All four tables are in .rodata; its section and PT_LOAD segment have no WRITE flag.')

def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--cc', help='Path to RISC-V GCC, clang, or zig executable')
    parser.add_argument('--source-only', action='store_true', help='Generate the editor copy without compiling')
    parser.add_argument('--render', action='store_true', help='Build the LED GUI ELF (requires --led-base)')
    parser.add_argument('--led-base', type=lambda s: int(s, 0), help='LED_MATRIX_0_BASE shown in Ripes I/O')
    args = parser.parse_args()
    compatibility_copy()
    compatibility_copy(render=True)
    if args.source_only:
        print('Generated solver_rv32i_ripes.s (editor compatibility, writable .data).')
        return
    compiler = args.cc or shutil.which('riscv64-unknown-elf-gcc') or shutil.which('riscv32-unknown-elf-gcc')
    if not compiler:
        candidates = list((ROOT / '.tools').glob('zig*/zig.exe'))
        compiler = str(candidates[0]) if candidates else None
    if not compiler:
        parser.error('No cross compiler found. Supply --cc PATH or install a RISC-V toolchain.')
    name = Path(compiler).name.lower()
    source_path = ROOT / 'solver_rv32i.s'
    output_path = ROOT / 'solver_rv32i.elf'
    if args.render:
        if args.led_base is None or not 0 <= args.led_base <= 0xffffffff or args.led_base % 4:
            parser.error('--render requires an aligned 32-bit --led-base from Ripes I/O')
        source = source_path.read_text(encoding='utf-8').replace('.equ RENDER, 0', '.equ RENDER, 1')
        source = ('.equ LED_MATRIX_0_BASE, %d\n.equ LED_MATRIX_0_WIDTH, 35\n'
                  '.equ LED_MATRIX_0_HEIGHT, 25\n' % args.led_base) + source
        temporary = ROOT / '.build' / 'led'
        temporary.mkdir(parents=True, exist_ok=True)
        source_path = temporary / 'gui_source.s'
        source_path.write_text(source, encoding='utf-8')
        output_path = ROOT / 'solver_rv32i_led.elf'
    command = [compiler]
    if name in ('zig', 'zig.exe'):
        # Zig interprets -march as a CPU name. generic_rv32 has no extensions.
        command += ['cc', '-target', 'riscv32-freestanding-none', '-mcpu=generic_rv32']
    elif 'clang' in name:
        command += ['--target=riscv32-unknown-elf', '-fuse-ld=lld']
    if name not in ('zig', 'zig.exe'):
        command += ['-march=rv32i', '-Wl,--no-relax', '-Wl,--build-id=none']
    command += ['-mabi=ilp32', '-mno-relax', '-nostdlib',
                '-Wl,-T,' + str(ROOT / 'solver_rv32i.ld'),
                str(source_path), '-o', str(output_path)]
    env = os.environ.copy()
    if name in ('zig', 'zig.exe'):
        env['ZIG_GLOBAL_CACHE_DIR'] = str(ROOT / '.tools' / 'zig-global-cache')
        env['ZIG_LOCAL_CACHE_DIR'] = str(ROOT / '.tools' / 'zig-local-cache')
    subprocess.run(command, cwd=str(ROOT), env=env, check=True)
    verify_elf(output_path)

if __name__ == '__main__':
    main()
