/*
 * check_h1.c
 *
 * H1 correctness gate:
 *
 *     h(s) <= d(s)
 *
 * for every one of the 3,674,160 states.
 *
 * The exact table is generated by the TA baseline solver.
 * The heuristic is taken from the student's solver:
 *
 *     h(s) = max(pdb_permutation[p], pdb_orientation[o])
 *
 * Compile:
 *
 *     gcc check_h1.c -o check_h1
 *
 * Run:
 *
 *     ./check_h1
 *
 * Required files:
 *
 *     check_h1.c
 *     solver_baseline.c
 *     pdb_tables.h
 */

#include <stdio.h>
#include <stdint.h>
#include <stdlib.h>

/*
 * Rename the baseline main() so that we can include
 * solver_baseline.c directly in this file.
 *
 * All of the baseline functions are static, so after
 * inclusion they are available to this translation unit.
 */
#define main baseline_main
#include "solver_baseline.c"
#undef main

/*
 * Your PDB tables.
 *
 * This is the same header used by solver.c.
 */
#include "pdb_tables.h"


/* --------------------------------------------------------- */
/* Check the heuristic used by solver.c                      */
/* --------------------------------------------------------- */

static uint8_t heuristic_from_rank(uint32_t rank)
{
    /*
     * rank = p * ORIENTATIONS + o
     */
    uint16_t p = (uint16_t)(rank / ORIENTATIONS);
    uint16_t o = (uint16_t)(rank % ORIENTATIONS);

    uint8_t h_perm = pdb_permutation[p];
    uint8_t h_ori  = pdb_orientation[o];

    return (h_perm > h_ori) ? h_perm : h_ori;
}


/* --------------------------------------------------------- */
/* Calculate exact distance using the baseline table         */
/* --------------------------------------------------------- */

static uint8_t exact_distance_from_table(
    uint32_t rank,
    const uint8_t *table)
{
    uint8_t distance = 0;

    /*
     * The baseline table stores the move that takes
     * the current state one step closer to the solved state.
     *
     * Therefore, repeatedly applying table[rank] must
     * eventually reach rank 0.
     */
    while (rank != 0) {

        uint8_t move = table[rank];

        state_t state;
        unrank_state(rank, &state);

        state = apply_move(state, move);

        rank = rank_state(&state);

        ++distance;

        /*
         * The baseline cube has diameter 11.
         * This protects against an accidentally corrupted
         * table causing an infinite loop.
         */
        if (distance > 11) {
            fprintf(stderr,
                    "ERROR: table path exceeded diameter 11\n");
            exit(EXIT_FAILURE);
        }
    }

    return distance;
}


/* --------------------------------------------------------- */
/* H1 checker                                                */
/* --------------------------------------------------------- */

int main(void)
{
    uint8_t diameter;

    printf("Building exact table using solver_baseline.c...\n");

    uint8_t *table = build_table(&diameter);

    if (table == NULL) {
        fprintf(stderr,
                "ERROR: baseline could not build complete table.\n");
        return EXIT_FAILURE;
    }

    printf("Baseline table built successfully.\n");
    printf("States : %d\n", STATES);
    printf("Diameter : %u\n", diameter);

    /*
     * The baseline is expected to cover the entire state space
     * and have diameter 11.
     */
    if (diameter != 11) {
        fprintf(stderr,
                "ERROR: expected diameter 11, got %u\n",
                diameter);

        free(table);
        return EXIT_FAILURE;
    }

    printf("\nChecking H1:\n");
    printf("    h(s) <= d(s)\n");
    printf("for all %d states...\n\n", STATES);

    uint32_t checked = 0;
    uint32_t violations = 0;

    uint8_t max_h = 0;
    uint8_t max_d = 0;

    uint32_t worst_rank = 0;
    uint8_t worst_h = 0;
    uint8_t worst_d = 0;

    for (uint32_t rank = 0; rank < STATES; ++rank) {

        /*
         * Student heuristic.
         */
        uint8_t h = heuristic_from_rank(rank);

        /*
         * Exact shortest distance obtained from
         * the TA baseline BFS table.
         */
        uint8_t d = exact_distance_from_table(rank, table);

        ++checked;

        if (h > max_h)
            max_h = h;

        if (d > max_d)
            max_d = d;

        /*
         * H1 violation:
         *
         *     h(s) > d(s)
         */
        if (h > d) {

            ++violations;

            printf("H1 violation:\n");
            printf("    rank = %u\n", rank);
            printf("    h(s) = %u\n", h);
            printf("    d(s) = %u\n\n", d);

            /*
             * Keep track of the largest violation.
             */
            if ((uint8_t)(h - d) >
                (uint8_t)(worst_h - worst_d)) {

                worst_rank = rank;
                worst_h = h;
                worst_d = d;
            }
        }
    }

    printf("========================================\n");
    printf("H1 CHECK RESULT\n");
    printf("========================================\n");

    printf("States checked         : %u\n", checked);
    printf("Expected states        : %u\n", STATES);
    printf("Maximum heuristic h(s) : %u\n", max_h);
    printf("Maximum exact d(s)      : %u\n", max_d);
    printf("H1 violations          : %u\n", violations);

    if (violations == 0) {

        printf("\n");
        printf("H1 PASS:\n");
        printf("h(s) <= d(s) for every state.\n");

        free(table);
        return EXIT_SUCCESS;
    }

    printf("\n");
    printf("H1 FAIL.\n");
    printf("Worst violation:\n");
    printf("    rank = %u\n", worst_rank);
    printf("    h(s) = %u\n", worst_h);
    printf("    d(s) = %u\n", worst_d);

    free(table);
    return EXIT_FAILURE;
}